version: 0.1
log:
  level: debug
  fields:
    service: registry
    environment: development
storage:
    cache:
        blobdescriptor: redis
    filesystem:
        rootdirectory: /var/lib/registry-cache
    maintenance:
        uploadpurging:
            enabled: false
    tag:
      concurrencylimit: 8
http:
    addr: :5000
    secret: asecretforlocaldevelopment
    debug:
        addr: localhost:5001
    headers:
        X-Content-Type-Options: [nosniff]
redis:
  addrs: [localhost:6379]
  maxidleconns: 16
  poolsize: 64
  connmaxidletime: 300s
  dialtimeout: 10ms
  readtimeout: 10ms
  writetimeout: 10ms
notifications:
    events:
        includereferences: true
    endpoints:
        - name: local-8082
          url: http://localhost:5003/callback
          headers:
             Authorization: [Bearer <an example token>]
          timeout: 1s
          threshold: 10
          backoff: 1s
          disabled: true
        - name: local-8083
          url: http://localhost:8083/callback
          timeout: 1s
          threshold: 10
          backoff: 1s
          disabled: true
proxy:
  remoteurl: https://registry-1.docker.io
  username: username
  password: password
  remotehostquerykey: ns
  remotehostconfigmap:
    registry.k8s.io:
      remoteurl: https://registry.k8s.io
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
