version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    cooldown:
      default-days: 7
    groups:
      codeql-actions:
        patterns:
          - "github/codeql-action/*"
      docker-actions:
        patterns:
          - "docker/*"
