linters:
  enable:
    - staticcheck
    - unconvert
    - gofmt
    - goimports
    - revive
    - ineffassign
    - govet
    - unused
    - misspell
    - bodyclose
    - prealloc
    - errcheck
    - tparallel

linters-settings:
  revive:
    rules:
      # TODO(thaJeztah): temporarily disabled the "unused-parameter" check.
      # It produces many warnings, and some of those may need to be looked at.
      - name: unused-parameter
        disabled: true

issues:
  deadline: 2m
  exlude-dirs:
    - vendor
