# This project makefile is around for generating peices of documentation and
# code. For most purposes, running it is not necessary.

.PHONY: clean
.DEFAULT: default

default:
	@echo Please read the make targets before using this Makefile. It is \
	    currently only used for documentation and autogenerated files.

AUTHORS: .mailmap .git/ORIG_HEAD .git/FETCH_HEAD .git/HEAD
	 git log --format='%aN <%aE>' | sort -fu >> $@

clean:
	rm -rf AUTHORS