#!/usr/bin/env bash

set -eu -o pipefail

if ! command -v git-validation; then
    >&2 echo "ERROR: git-validation not found. Install with:"
    >&2 echo "    go install github.com/vbatts/git-validation@latest"
    exit 1
fi

verbosity="${DCO_VERBOSITY--v}"
GIT_CHECK_EXCLUDE="./vendor:./script/validate/template" git-validation "$verbosity" -range "5b98226afefa11a06ef0c652af4995177c0efda0..HEAD" -run DCO,short-subject,dangling-whitespace