#!/usr/bin/env bash

set -eu -o pipefail

go mod tidy
rm -rf vendor/
go mod vendor

DIFF_PATH="vendor/"
DIFF=$(git status --porcelain -- "$DIFF_PATH")

if [ "$DIFF" ]; then
    echo
    echo "These files were modified:"
    echo
    echo "$DIFF"
    echo
    exit 1
else
    echo "$DIFF_PATH is correct"
fi
