#!/bin/bash

if [ -z "$1" ] && [ -z "$2" ]
then
cat << HELP

NAME
     migrateimages - move all tagged images to a destination registry

SYNOPSIS
     migrateimages [image_name] [destination_registry]

DESCRIPTION
     The migrateimages utility pulls images from the primary registry configured with docker (ie. dockerhub, quay, etc),
     pulls down the images and moves them to a destination registry.

EXAMPLE: 
    - move all images for ubuntu to a registry at 127.0.0.1:5005:
       migrateimages ubuntu 127.0.0.1:5005

HELP
exit 1 
fi

original_image="$1"
target_acr="$2"

# Download all images
docker pull $original_image --all-tags

# Get all images published after $minimum_version
# format output to be: 
#   docker tag ORIGINAL_IMAGE_NAME:VERSION TARGET_IMAGE_NAME:VERSION |
#   docker push TARGET_IMAGE_NAME:VERSION
# then filter the result, removing any entries containing words defined on $grep_filter (i.e. rc, beta, alpha, etc)
# finally, execute those as commands
docker images $original_image \
  --format "docker tag {{.Repository}}:{{.Tag}} $target_acr/{{.Repository}}:{{.Tag}} | docker push $target_acr/{{.Repository}}:{{.Tag}}" | 
  bash