#!/usr/bin/env bash

GOLANGCI_LINT_VERSION="v1.44.0"

#
# Install developer tools to $GOBIN (or $GOPATH/bin if unset)
#
set -eu -o pipefail

# Enable Go modules
export GO111MODULE=on

# prevent updating go.mod of the project
cd /tmp
go get "github.com/golangci/golangci-lint/cmd/golangci-lint@${GOLANGCI_LINT_VERSION}"
