name: Pull Request Labeler

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request_target: # zizmor: ignore[dangerous-triggers] does not checkout, safe to use pull_request_target

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  labeler:
    permissions:
      contents: read       # same as global permission
      pull-requests: write # required for writing labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6.0.1
        with:
          dot: true
